"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, Filter, Trophy } from "lucide-react";
import { supabase } from "../../../lib/supabase";
import { Button, Input, PageHeader, Panel, Select } from "../components/ui";

function csv(rows:any[]){const header=["Rank","Union","College","Academic Year","Dawa","Adarsham","Sargam","Publishing","Total"];const body=rows.map((r,i)=>[i+1,r.union_name,r.college_name,r.academic_year,r.dawa_score,r.adarsham_score,r.sargam_score,r.publishing_score,r.total_score]);return [header,...body].map(x=>x.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n")}

export default function LeaderboardPage(){const [rows,setRows]=useState<any[]>([]);const [year,setYear]=useState("all");const [q,setQ]=useState("");useEffect(()=>{supabase.from("union_metrics").select("*").order("total_score",{ascending:false}).then(({data})=>setRows(data??[]))},[]);const years=[...new Set(rows.map(r=>r.academic_year).filter(Boolean))];const filtered=rows.filter(r=>(year==="all"||r.academic_year===year)&&(!q||`${r.union_name} ${r.college_name}`.toLowerCase().includes(q.toLowerCase())));const exportCsv=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv(filtered)],{type:"text/csv"}));a.download="sajda-leaderboard.csv";a.click();};return <div><PageHeader eyebrow="Standings" title="Leaderboard" description="Live ranking sourced directly from the calculated union metrics view." actions={<Button variant="ghost" onClick={exportCsv}><Download size={15}/> Export CSV</Button>}/><Panel><div className="mb-5 grid gap-3 md:grid-cols-[1fr_200px]"><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search union or college..."/><Select value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{years.map(y=><option key={y}>{y}</option>)}</Select></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b border-white/10 text-[10px] uppercase tracking-wider text-white/30"><tr><th className="px-3 py-3">Rank</th><th>Union</th><th>College</th><th>Da</th><th>Ad</th><th>Sa</th><th>Pu</th><th className="text-right">Total</th></tr></thead><tbody className="divide-y divide-white/5">{filtered.map((r,i)=><tr key={r.union_id}><td className="px-3 py-4"><div className={`grid h-8 w-8 place-items-center rounded-lg ${i<3?"bg-amber-400/10 text-amber-300":"bg-white/5 text-white/40"}`}><Trophy size={15}/></div><div className="mt-1 text-[10px] font-black text-white/30">{i+1}</div></td><td className="font-black">{r.union_name}</td><td className="text-white/45">{r.college_name}</td><td>{r.dawa_score}</td><td>{r.adarsham_score}</td><td>{r.sargam_score}</td><td>{r.publishing_score}</td><td className="text-right font-black text-amber-300">{r.total_score}</td></tr>)}</tbody></table></div></Panel></div>}
