"use client";

import { useEffect, useState } from "react";
import { Download, FileBarChart2, Printer } from "lucide-react";
import { supabase } from "../../../lib/supabase";
import { Button, PageHeader, Panel } from "../components/ui";

function toCsv(rows:any[]){if(!rows.length)return "";const keys=Object.keys(rows[0]);return [keys,...rows.map(r=>keys.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`))].map(r=>r.join(",")).join("\n")}
export default function ReportsPage(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from("union_metrics").select("*").order("total_score",{ascending:false}).then(({data})=>setRows(data??[]))},[]);const exportCsv=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([toCsv(rows)],{type:"text/csv"}));a.download="sajda-union-report.csv";a.click()};return <div><PageHeader eyebrow="Data & reporting" title="Reports" description="Operational report exports for current union performance and administration." actions={<><Button onClick={exportCsv}><Download size={15}/> Export CSV</Button><Button variant="ghost" onClick={()=>window.print()}><Printer size={15}/> Print</Button></>}/><div className="grid gap-4 md:grid-cols-3"><Panel><FileBarChart2 className="text-amber-300"/><div className="mt-4 text-2xl font-black">{rows.length}</div><div className="text-xs text-white/35">Union rows</div></Panel><Panel><div className="text-xs font-black uppercase tracking-wider text-white/35">Total points</div><div className="mt-4 text-2xl font-black">{rows.reduce((a,r)=>a+Number(r.total_score||0),0)}</div></Panel><Panel><div className="text-xs font-black uppercase tracking-wider text-white/35">Average</div><div className="mt-4 text-2xl font-black">{rows.length?Math.round(rows.reduce((a,r)=>a+Number(r.total_score||0),0)/rows.length):0}</div></Panel></div><Panel className="mt-6"><h3 className="mb-4 font-black">Report preview</h3><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-white/10 text-[10px] uppercase tracking-wider text-white/30"><tr><th className="px-3 py-3">Union</th><th>College</th><th>Year</th><th>Da</th><th>Ad</th><th>Sa</th><th>Pu</th><th>Total</th></tr></thead><tbody className="divide-y divide-white/5">{rows.map(r=><tr key={r.union_id}><td className="px-3 py-3 font-bold">{r.union_name}</td><td className="text-white/45">{r.college_name}</td><td>{r.academic_year}</td><td>{r.dawa_score}</td><td>{r.adarsham_score}</td><td>{r.sargam_score}</td><td>{r.publishing_score}</td><td className="font-black text-amber-300">{r.total_score}</td></tr>)}</tbody></table></div></Panel></div>}
